### ISSUE TITLE
Front End / Glue / UI

### ISSUE THREAD

**Issue by charlesdaniels** [TaylorLCling/csce567Project#3]
A top-level front end / glue setup needs to be created. This should:

* Display the drawing area
* Allow selecting between the three visualizations noted in the README
* Load the data file and send it into the appropriate function calls

**Comment by TaylorLCling** [comment]
-Displayed Drawing Area 682ddf141f1d15f735209baa64d43cc7dd7e6344
-Allowed Selection of three different visualizations 1476be92450c2457d07b6f17cba59ca9b70114de
-Set loading of Data to end with saving to an accessible variable, now functions only need to call that variable 2dbf6c978703cc3987b43fbaa083c95199aaf2e0
